### ISSUE TITLE
ObjectManagerInterface::get() invoked with N parameters, 1 required

### ISSUE THREAD

**Issue by mbrodala** [sascha-egerer/phpstan-typo3#19] opened 2020-02-19 16:28 UTC
Would it be possible to let PHPStan accept calls to `ObjectManager(Interface)::get()` with constructor arguments? Currently an error is shown:

> ObjectManagerInterface::get() invoked with N parameters, 1 required

Such a call looks like `$objectManager->get(Foo::class, 'bar')`.

**Comment by sascha-egerer** [comment] 2020-02-19 17:02
I can't reproduce that. Could you please post your exact configuration and the code where it fails? 

https://phpstan.org/r/41ed91ea-433a-4409-a90b-9efe820301d8

**Comment by mbrodala** [comment] 2020-02-20 13:31
Ah sorry, I didn't notice that this was fixed for TYPO3v9 and newer. In TYPO3v8 variadic arguments are not used, so `get()` expects exactly one argument and uses `func_get_args()`.

**Comment by sascha-egerer** [comment] 2020-02-20 13:38
Ah ok, makes sense. So we could fix that here but i would suggest to add an ignore for this error message to your project configuration.

**Comment by mbrodala** [comment] 2020-02-20 13:41
Yep, that's what we did. :-)

**Comment by sascha-egerer** [comment] 2020-02-20 14:11
Ok, so i think it's fine to close this ticket, right?

**Closed by sascha-egerer** 2020-02-20 14:11 UTC

**Comment by mbrodala** [comment] 2020-02-20 14:16
Yeah, probably not worth the effort for TYPO3v8 only.
