### ISSUE TITLE
[Bug] Error when calling `toArray()` on repository method in controller

### ISSUE THREAD

**Issue by dahaupt** [sascha-egerer/phpstan-typo3#103] opened 2022-10-23 22:31 UTC
Since the latest version v1.8.0 we get this error when running PHPStan:

```
Internal error: Internal error: Repository class "Vendor\Package\Controller\MyController" must implement "TYPO3\CMS\Extbase\Persistence\RepositoryInterface" in file 
     /var/www/html/packages/package/Classes/MyController.php

[...]

#0 /var/www/html/vendor/saschaegerer/phpstan-typo3/src/Type/QueryResultToArrayDynamicReturnTypeExtension.php(52):                                                                                                   
     SaschaEgerer\PhpstanTypo3\Type\QueryResultToArrayDynamicReturnTypeExtension->translateRepositoryNameToModelName('Vendor\\MyPackage...')
```

Related line:
```php
$items = $this->myRepository->findAll()->toArray();
```

**Comment by sascha-egerer** [comment] 2022-10-24 10:49
I wonder a bit why MyController should implement the RepositorfyInterface - this does not make sense. Do you have more details or maybe also code to reproduce it?

**Comment by the-coding-owl** [comment] 2022-10-24 10:52
Hi @sascha-egerer 

I am also encountering the issue right now and it originates in SaschaEgerer\PhpstanTypo3\Type\QueryResultToArrayDynamicReturnTypeExtension at line 51 when calling translateRepositoryNameToModelName

Apperently the parameter given to this function must be of a repository class name. Given is the class name of the class in which the toArray call is taking place.

**Comment by sascha-egerer** [comment] 2022-10-24 10:52
Ah ok - got it. I'll have a look.

**Comment by dahaupt** [comment] 2022-10-24 11:16
@sascha-egerer I already did some debugging:

[src/Type/QueryResultToArrayDynamicReturnTypeExtension.php:44](https://github.com/sascha-egerer/phpstan-typo3/blob/master/src/Type/QueryResultToArrayDynamicReturnTypeExtension.php#L44-L46)
```php
if ($resultType instanceof GenericObjectType) {
    $modelType = $resultType->getTypes();
}
```

The `$resultType` is now of type `ObjectType` so that the condition is never true.

**Comment by the-coding-owl** [comment] 2022-10-24 11:16
To reproduce the issue it should be enough to create a quick Extbase extension with a model, a repository and a controller and then fetchAll and toArray the QueryResult in the controller instead of the Repository.

**Comment by sascha-egerer** [comment] 2022-10-26 20:03
@dahaupt Could you please confirm that the latest release did fix the issue?

**Comment by dahaupt** [comment] 2022-10-27 12:51
@sascha-egerer Hello, I just tested the new release. It does not solve the problem in our project. 

However, I discovered that the problem occurs only with TYPO3 v10. We are currently updating the project to v11 and in the instance the problem does not occur at all (not even with v1.8.0).

**Comment by sascha-egerer** [comment] 2022-10-27 19:21
@dahaupt Interesting... but i can't reproduce it with TYPO3 v10 in the tests... Do you have any annotations at your `findAll()` method?

**Comment by dahaupt** [comment] 2022-10-28 18:34
@sascha-egerer Yes, my repository method has the return type `QueryResultInterface`. It is working if I additionally add the PHPDoc annotation `@return QueryResultInterface<MyEntity>`.

**Comment by sascha-egerer** [comment] 2022-10-30 19:13
> @sascha-egerer Yes, my repository method has the return type `QueryResultInterface`. It is working if I additionally add the PHPDoc annotation `@return QueryResultInterface<MyEntity>`.

Ok - thats the issue. I can also reproduce it now.

**Comment by sascha-egerer** [comment] 2022-10-31 10:42
I think the real problem is in https://github.com/sascha-egerer/phpstan-typo3/blob/master/src/Type/RepositoryFindAllDynamicReturnTypeExtension.php#L41-L53
If there is a custom findAll() without a correct annotation is implemented, it'll not work.

So the current workaround is to define an explicit return type if a custom findAll method is implemented.

I'm sorry but i have to time to investigate further right now - maybe someone else can have a look.

**Comment by sascha-egerer** [comment] 2022-11-15 19:52
@dahaupt I think this should be solved now in master. Would be cool if you could test your cases with it. I'll close this ticket now. Feel free to create a new one if something is still broken.

**Closed by sascha-egerer** 2022-11-15 19:52 UTC

**Comment by dahaupt** [comment] 2022-11-19 07:56
@sascha-egerer I can confirm it is working now in our project. Thanks for providing a solution!

**Comment by sascha-egerer** [comment] 2022-11-19 08:09
👍🏻
