### ISSUE TITLE
Internal error in TYPO3 Repositories

### ISSUE THREAD

**Issue by mafl** [sascha-egerer/phpstan-typo3#115] opened 2023-03-15 22:50 UTC
Hi,

try to check the Repositories in my own Project and get the following error:
``Internal error: Internal error: Repository class "T3docs\BlogExample\Domain\Repository\PostRepository" must implement "TYPO3\CMS\Extbase\Persistence\RepositoryInterface" in file
     /Users/martin/Sites/classictypo/htdocs/typo3conf/ext/blog_example/Classes/Domain/Repository/PostRepository.php``

so i try to check the official example Extension "BlogExample" and get the same error.
Here the Stacktrace:
```
#0 /Users/martin/Sites/classictypo/vendor/saschaegerer/phpstan-typo3/src/Type/RepositoryQueryDynamicReturnTypeExtension.php(53):
     SaschaEgerer\PhpstanTypo3\Type\RepositoryQueryDynamicReturnTypeExtension->translateRepositoryNameToModelName('T3docs\\BlogExam...')
     #1 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3344):
     SaschaEgerer\PhpstanTypo3\Type\RepositoryQueryDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall),
     Object(PHPStan\Analyser\MutatingScope))
     #2 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ThisType), 'createQuery',
     Object(PhpParser\Node\Expr\MethodCall))
     #3 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
     #4 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType('$this->createQu...', Object(PhpParser\Node\Expr\MethodCall))
     #5 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(742): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
     #6 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType('$query = $this-...', Object(PhpParser\Node\Expr\Assign))
     #7 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1465): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Assign))
     #8 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(559): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\Assign),
     Object(PHPStan\Analyser\MutatingScope))
     #9 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression),
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
     #10 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(523): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
     #11 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),
     Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
     #12 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(601): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,
     Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
     #13 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
     #14 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(573): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array,
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
     #15 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(331): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
     #16 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope),
     Object(Closure))
     #17 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(130): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/martin/S...', Array, Object(PHPStan\Rules\LazyRegistry),
     Object(PHPStan\Collectors\Registry), NULL)
     #18 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
     #19 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_1292afebc\Evenement\EventEmitter->emit('data', Array)
     #20 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_1292afebc\Clue\React\NDJson\Decoder->handleData(Array)
     #21 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_1292afebc\Evenement\EventEmitter->emit('data', Array)
     #22 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_1292afebc\React\Stream\Util::_PHPStan_1292afebc\React\Stream\{closure}('{"action":"anal...')
     #23 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_1292afebc\Evenement\EventEmitter->emit('data', Array)
     #24 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_1292afebc\React\Stream\DuplexResourceStream->handleData(Resource id #6424)
     #25 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_1292afebc\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
     #26 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_1292afebc\React\EventLoop\StreamSelectLoop->run()
     #27 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):
     PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_1292afebc\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1292afebc\Symfony\Component\Console\Output\ConsoleOutput))
     #28 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):
     _PHPStan_1292afebc\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_1292afebc\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1292afebc\Symfony\Component\Console\Output\ConsoleOutput))
     #29 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261):
     _PHPStan_1292afebc\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand), Object(_PHPStan_1292afebc\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_1292afebc\Symfony\Component\Console\Output\ConsoleOutput))
     #30 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
     _PHPStan_1292afebc\Symfony\Component\Console\Application->doRun(Object(_PHPStan_1292afebc\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1292afebc\Symfony\Component\Console\Output\ConsoleOutput))
     #31 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_1292afebc\Symfony\Component\Console\Application->run()
     #32 phar:///Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_1292afebc\{closure}()
     #33 /Users/martin/Sites/classictypo/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/m...')
     #34 /Users/martin/Sites/classictypo/vendor/bin/phpstan(120): include('/Users/martin/S...')
     #35 {main}
     Child process error (exit code 1):
```

I didn't change anything in the PostRepository.php:
```<?php
declare(strict_types=1);

namespace T3docs\BlogExample\Domain\Repository;

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

use T3docs\BlogExample\Domain\Model\Blog;
use T3docs\BlogExample\Domain\Model\Post;
use TYPO3\CMS\Extbase\Persistence\QueryInterface;
use TYPO3\CMS\Extbase\Persistence\QueryResultInterface;
use TYPO3\CMS\Extbase\Persistence\Repository;

/**
 * A repository for blog posts
 *
 * @method Post findByUid($uid)
 */
class PostRepository extends Repository
{
    protected $defaultOrderings = ['date' => QueryInterface::ORDER_DESCENDING];

    /**
     * Finds all posts by the specified blog
     *
     * @param Blog $blog The blog the post must refer to
     */
    public function findAllByBlog(Blog $blog): QueryResultInterface
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->equals('blog', $blog)
            )
            ->execute();
    }

    /**
     * Finds posts by the specified tag and blog
     *
     * @param Blog $blog The blog the post must refer to
     */
    public function findByTagAndBlog(string $tag, Blog $blog): QueryResultInterface
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->logicalAnd(
                    $query->equals('blog', $blog),
                    $query->equals('tags.name', $tag)
                )
            )
            ->execute();
    }

    /**
     * Finds all remaining posts of the blog
     *
     * @param Post $post The reference post
     */
    public function findRemaining(Post $post): QueryResultInterface
    {
        $blog = $post->getBlog();
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->logicalAnd(
                    $query->equals('blog', $blog),
                    $query->logicalNot(
                        $query->equals('uid', $post->getUid())
                    )
                )
            )
            ->execute();
    }

    /**
     * Finds the previous of the given post
     *
     * @param Post $post The reference post
     */
    public function findPrevious(Post $post): ?Post
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->lessThan('date', $post->getDate())
            )
            ->execute()
            ->getFirst();
    }

    /**
     * Finds the post next to the given post
     *
     * @param Post $post The reference post
     */
    public function findNext(Post $post): ?Post
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->greaterThan('date', $post->getDate())
            )
            ->execute()
            ->getFirst();
    }

    /**
     * Finds most recent posts by the specified blog
     *
     * @param Blog $blog The blog the post must refer to
     * @param int $limit The number of posts to return at max
     */
    public function findRecentByBlog(Blog $blog, int $limit = 5): QueryResultInterface
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->equals('blog', $blog)
            )
            ->setLimit((int)$limit)
            ->execute();
    }

    public function findByCategory(int $categoryUid): QueryResultInterface
    {
        $query = $this->createQuery();
        return $query
            ->matching(
                $query->contains('categories', $categoryUid)
            )
            ->execute();
    }

    public function findAllSortedByCategory(array $uids): QueryResultInterface
    {
        $q = $this->createQuery();
        $q->matching($q->in('uid', $uids));
        $q->setOrderings([
            'categories.title' => QueryInterface::ORDER_ASCENDING,
            'uid' => QueryInterface::ORDER_ASCENDING,
        ]);
        return $q->execute();
    }
}
```
Please could somebody help?

**Comment by sascha-egerer** [comment] 2023-03-17 20:51
Looks like there is something wrong with autoloader or phpstan configuration. Could you please post your composer.json and phpstan configuration?

**Comment by mafl** [comment] 2023-03-18 06:57
Hello Sascha, thank you for your help.
Here the composer.json
```
{
    "require-dev": {
        "typo3/coding-standards": "^0.7.1",
        "ssch/typo3-rector": "^1.1",
        "vimeo/psalm": "^5.7",
        "phpstan/phpstan": "^1.10",
        "saschaegerer/phpstan-typo3": "^1.8",
        "phpstan/extension-installer": "^1.2"
    },
    "config": {
        "allow-plugins": {
            "typo3/cms-composer-installers": true,
            "typo3/class-alias-loader": true,
            "phpstan/extension-installer": true
        }
    }
}
```
and the phpstan.neon
```
parameters:
	level: 6
	paths:
		- htdocs/typo3conf/ext/blog_example/
	scanDirectories:
		- htdocs/typo3_src
```

**Comment by sascha-egerer** [comment] 2023-03-18 08:32
First of all scanDirectories should not be required. In your composer.json you're do not require the blog_example extension. How does your folder structure look like? You said it's reproducible with the blog extension. So could you please provide a composer.json and phpstan.neon with correct paths so i can try to reproduce it? The htdocs/typo3_src and htdocs/typo3conf/ext/blog_example/ looks it bit weird to me. Maybe we can also switch to `#typo3-phpstan` channel in TYPO3 Slack as i think it's more a understanding/configuration related problem.

**Comment by sascha-egerer** [comment] 2023-04-12 21:19
I'll close this issue due to missing feedback.

**Closed by sascha-egerer** 2023-04-12 21:19 UTC
